spring:  application:    name: user-serviceeureka:   client:       register-with-eureka: true       fetch-registry: true       serviceUrl:         defaultZone: http://localhost:1000/eureka/   instance:       preferIpAddress: trueserver:
  port: 8080
  contextPath: /api/user